### ISSUE TITLE
Problems when using these models in Gazebo

### ISSUE THREAD

**Issue by S-Dafarra** [robotology-playground/icub-models#7]
While using the ``icub-models`` in Gazebo I encountered the following problems:
- [x] The inertias of some links are too small and need to be modified by hand as suggested in [this comment](https://github.com/robotology-playground/icub-model-generator/issues/52#issuecomment-338957495) => solved by https://github.com/robotology-playground/icub-model-generator/pull/71.
- [x] When the robot is inserted in Gazebo, it is "submerged" in the ground and needs to be moved by hand pausing Gazebo beforehand => this is because the models in the repo `icub-models` don't have the offset positioning the model in the world. This offset is defined within the models defined in [icub-gazebo-wholebody](https://github.com/robotology-playground/icub-gazebo-wholebody).
- [x] Once I press play on Gazebo with the robot correctly placed, Gazebo crashes. See [this comment](https://github.com/robotology-playground/icub-models/issues/5#issuecomment-339034743) => only occurs if we insert in Gazebo the new model **iCubGazeboV2_5** directly from the `icub-models` repo, and not through `icub-gazebo-wholebody`. This issue is not blocking and shall be tracked by https://github.com/robotology-playground/icub-models/issues/10. All models in `icub-gazebo-wholebody` will be updated in order to point to the new model **iCubGazeboV2_5**.
- [x] Both the wrist yaw joints go in hardware fault. Apparently the position control is unstable and it brings the joints toward the limits. I tried to reduce the gains, but it did not work => will be tracked in the Epic [icub-model-generator/#52](https://github.com/robotology-playground/icub-model-generator/issues/52).

Cc.
@nunoguedelha @traversaro @diegoferigo @francesco-romano @fiorisi @DanielePucci

**Comment by traversaro** [comment]
* [ ] The meshes in the foot should be substituted with a simpler primitive shapes (box or four spheres)

**Comment by traversaro** [comment]
> Both the wrist yaw joints go in hardware fault. Apparently the position control is unstable and it brings the joints toward the limits. I tried to reduce the gains, but it did not work. 

With @nunoguedelha we looked into computing gazebo gains nominally equivalent to the real robot gains. I think we should set the gain on the Gazebo models that are approximately equivalent to the real robot one.

**Comment by S-Dafarra** [comment]
@traversaro I tried to reduce them a lot. The only difference was that the joints did not go into HF, but they reached the same limit position.

**Comment by traversaro** [comment]
> @traversaro I tried to reduce them a lot. The only difference was that the joints did not go into HF, but they reached the same limit position.

Mhh. This does not seem just an gains issue.

**Comment by diegoferigo** [comment]
> When the robot is inserted in Gazebo, it is "submerged" in the ground and needs to be moved by hand pausing Gazebo beforehand

I thought that `icub-models` should contain only urdfs / meshes, and then [`icub-gazebo-wholebody`](https://github.com/robotology-playground/icub-gazebo-wholebody) is required for the configuration and placement of these models.

**Comment by traversaro** [comment]
> I thought that icub-models should contain only urdfs / meshes, and then icub-gazebo-wholebody is required for the configuration and placement of these models.

In theory icub-gazebo-wholebody was meant to be just a repository containing DIC/LOC2 specific stuff, while icub-gazebo and icub-models should be usable indipendently (as usual, all this decision can be changed). 
The offset of the robot was classically introduced in the converted SDF model by specifying explicitly the pose of the model (https://github.com/robotology/icub-gazebo/blob/master/icub/icub.sdf#L4). In some other projects distributing Gazebo models in URDF form, the strategy that I have used is to keep two Gazebo models: one without any YARP plugin, and a composite one that includes the raw one, adds the YARP plugins and the necessary offset. Unfortunately I don't have any example of this in public repositories.

**Comment by traversaro** [comment]
>  Once I press play on Gazebo with the robot correctly placed, Gazebo crashes. See this comment
This seems to be related to https://github.com/robotology-playground/icub-model-generator/issues/54 .

**Comment by traversaro** [comment]
> The inertias of some links are too small and need to be modified by hand as suggested in this comment.
Relative issue: https://github.com/robotology/icub-gazebo/issues/22 .

**Comment by traversaro** [comment]
I would also add to the problems that we should install configuration files only for `iCubGazeboV2_5`, as all other models are expected not to work.

**Comment by traversaro** [comment]
For some of this issue, opening a separate thread could improve the readability of the issue.

**Comment by S-Dafarra** [comment]
Maybe this issue should become an epic

**Comment by nunoguedelha** [comment]
@S-Dafarra @traversaro I've edited the first two comments of the issue for checking the solved problems. Remaining problems are also tracked in the issue that was opened in July and was tracking the work to be done for using the generated models on Gazebo (turned now into an Epic): [icub-model-generator/#52](https://github.com/robotology-playground/icub-model-generator/issues/52).

**Comment by S-Dafarra** [comment]
Thanks @nunoguedelha!! Maybe we can close this issue and point to https://github.com/robotology-playground/icub-model-generator/issues/52 in the [README](https://github.com/robotology-playground/icub-models/blob/master/README.md) of this repo to avoid duplicates. 

Can I also ask you some more details about
>not a real issue, was due to wrong environment variable setting (GAZEBO_MODEL_PATH)

Which folder should be added? Was it a problem in the placement of the configuration files?

**Comment by nunoguedelha** [comment]
Edited the original comment of the issue regarding the third listed problem.

**Comment by nunoguedelha** [comment]
The new models are now supported on Gazebo and have been tested. Any remaining improvements will continue to be tracked in https://github.com/robotology-playground/icub-model-generator/issues/52.
Closing this issue now.
